Update ffcompress

diff --git a/ffcompress b/ffcompress
--- a/ffcompress
+++ b/ffcompress
@@ -22,14 +22,14 @@ while getopts i:o:s:n:e: OPTION; do
 		EXT=$OPTARG
 		;;
 	\?)
-		echo "script usage: ffcompress [-i input] [-o output] [-s size in mb] [-n exported video name] [-e exported video extension]" >&2
+		echo "[!] Error: Wrong use of flags"
+		echo "Use ffcompress to get full help" >&2
 		exit 1
 		;;
 	esac
 done
 
 if test -f "$INPUT" && test -d "$OUTPUT"; then
-	echo "[+] File exists! Launching ffmpeg compress script"
 	outputname="${OUTPUT}/${filename%.*}-${SIZE}mb.${EXT}"
 	if [ "$NAME" != "" ]; then
 		outputname="${OUTPUT}/${NAME}.${EXT}"
@@ -42,6 +42,10 @@ if test -f "$INPUT" && test -d "$OUTPUT"; then
 	video_bitrate=$(( $total_bitrate - $audio_bitrate ))
 	ffmpeg -i "$INPUT" -b:v $video_bitrate -maxrate:v $video_bitrate -bufsize:v $(( $target_size / 20 )) -b:a $audio_bitrate "$outputname"
 else
-	echo "script usage: ffcompress [-i input] [-o output] [-s size in mb] [-n exported video name] [-e exported video extension]" >&2
-	exit 1
+	echo "FFCOMPRESS USAGE:"
+	echo "   -i   input video file"
+	echo "   -o   output video directory [default: input file dir]"
+	echo "   -s   exported video maximum size [mb, default: 8]"
+	echo "   -n   exported video name [default: FILENAME-Xmb]"
+	echo "   -e   extension of exported video file"
 fi
